services:
  nestapp:
    container_name: nestapp
    image: homelibrary/nestapp:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      TYPE: postgres
      POSTGRESS_HOST: db
      POSTGRESS_USER: postgres
      POSTGRESS_PASSWORD: password
      POSTGRESS_DATABASE: homelibrary
      POSTGRESS_PORT: 5432
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: homelibrary
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
